Report the origin function and drop method in FSA errors
In order for FSA to traverse through function calls inside the MIR, the
errors it emits must correctly identify the drop method that caused the
issue, and the current function. This commit adds support for this,
while making the errors reported a bit more user-friendly. For example:

This error:

```
error: `HasRef::default()` has a drop method which cannot be safely finalized.
  --> $DIR/references.rs:25:22
   |
LL |         use_val(self.c[0]); // should fail
   |                 ---------
   |                 |
   |                 caused by the expression in `fn drop(&mut)` here because
   |                 it uses a type which is not safe to use in a finalizer.
...
LL |     Gc::new(HasRef::default());
   |     --------^^^^^^^^^^^^^^^^^- `Gc::new` requires that [&u64; 2] implements the `FinalizeSafe` trait.
   |
   = help: `Gc` runs finalizers on a separate thread, so drop methods
           must only use values whose types implement `FinalizerSafe`.

```

Now becomes the much more readable:

```
error: The drop method for `HasRef<'_>` cannot be safely finalized.
  --> $DIR/references.rs:25:13
   |
LL |         use_val(self.c[0]); // should fail
   |                 ---------
   |                 |
   |                 a finalizer cannot safely use this `[&u64; 2]`
   |                 from a drop method because it does not implement `FinalizerSafe`.
...
LL |     Gc::new(HasRef::default());
   |     --------^^^^^^^^^^^^^^^^^- caused by trying to construct a `Gc<HasRef<'_>>` here.
   |
   = help: `Gc` runs finalizers on a separate thread, so drop methods
           must only use values whose types implement `FinalizerSafe`.

```

This commit also adds some extra tests for coverage.